//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSON.GTA.Tasks {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tasks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tasks() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSON.GTA.Tasks.Tasks", typeof(Tasks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 您没有购买该功能，请购买后再使用 的本地化字符串。
        /// </summary>
        internal static string NotAuthorization {
            get {
                return ResourceManager.GetString("NotAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在类型{0}中未能找到方法{1}. 的本地化字符串。
        /// </summary>
        internal static string NotFoundMehtod {
            get {
                return ResourceManager.GetString("NotFoundMehtod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务出现异常!请查看内部错误。 的本地化字符串。
        /// </summary>
        internal static string TaskException {
            get {
                return ResourceManager.GetString("TaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知任务 的本地化字符串。
        /// </summary>
        internal static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已全部处理完成，但有{0}个出错，请查看任务详情 的本地化字符串。
        /// </summary>
        internal static string TaskRecordCompletedButErrorMessage {
            get {
                return ResourceManager.GetString("TaskRecordCompletedButErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已全部处理完成 的本地化字符串。
        /// </summary>
        internal static string TaskRecordCompletedMessage {
            get {
                return ResourceManager.GetString("TaskRecordCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string TaskRecordDataExecuteFail {
            get {
                return ResourceManager.GetString("TaskRecordDataExecuteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string TaskRecordDataExecuteSuccess {
            get {
                return ResourceManager.GetString("TaskRecordDataExecuteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理第{0}/{1}条数据…… 的本地化字符串。
        /// </summary>
        internal static string TaskRecordMessage {
            get {
                return ResourceManager.GetString("TaskRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选中任何可操作项，或选中项已经全部操作完成 的本地化字符串。
        /// </summary>
        internal static string TaskRecordNoSelectedCanRunItems {
            get {
                return ResourceManager.GetString("TaskRecordNoSelectedCanRunItems", resourceCulture);
            }
        }
    }
}
