//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelTest.Style {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WheelTest.Style.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  package aa{
        /// public class JScript {
        /// public static function test(data,token,a,s) {
        ///	var i = &quot;//h5api.m.1688.com/h5/mtop.1688.shop.data.get/1.0/&quot;,
        ///		u = function(e) {
        ///			function t(e, t) {
        ///				return e &lt;&lt; t | e &gt;&gt;&gt; 32 - t
        ///			}
        ///
        ///			function o(e, t) {
        ///				var o, n, r, i, a;
        ///				return r = 2147483648 &amp; e,
        ///					i = 2147483648 &amp; t,
        ///					a = (1073741823 &amp; e) + (1073741823 &amp; t),
        ///					(o = 1073741824 &amp; e) &amp; (n = 1073741824 &amp; t) ? 2147483648 ^ a ^ r ^ i : o | n ? 1073741824 &amp; a ? 3221225472 ^ a ^ r ^ i [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _1688Token {
            get {
                return ResourceManager.GetString("_1688Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string baidufanyi {
            get {
                return ResourceManager.GetString("baidufanyi", resourceCulture);
            }
        }
    }
}
