//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelTest.CSDN.DailyExercise {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WheelTest.CSDN.DailyExercise.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 小艺酱又开学了，可是在上学的路上总会又各种意想不到的美食诱惑让小艺酱迟到。
        ///假设小艺酱家到学校是一个n*n的矩阵。
        ///每个格子包含一个诱惑值p，诱惑着小艺，让她迟到。
        ///小艺位于矩阵的左上角，学校在矩阵的右下角落。
        ///小艺想知道自己到达学校所要经历的最小诱惑值是？
        ///
        ///输入描述：
        ///
        ///第一行输入整数n。(1&lt;=n&lt;=100)
        ///以下n行每行有n个整数表示诱惑值。(1&lt;=p&lt;=100)
        ///
        ///输出描述：
        ///
        ///输出到达学校需要经历的最小诱惑值。
        ///
        ///输入样例：
        ///
        ///3
        ///1 3 7
        ///6 2 1
        ///9 8 0
        ///
        ///输出样例：
        ///
        ///7 的本地化字符串。
        /// </summary>
        internal static string _2023_2_18_1 {
            get {
                return ResourceManager.GetString("_2023_2_18_1", resourceCulture);
            }
        }
    }
}
